version: "3.9"

services:
  backend:
    build: 
      target: ${TARGET}

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT_INTERNAL}"

    volumes:
      - .:/api
      - /api/node_modules

    environment:
      - NODE_ENV=${NODE_ENV}